server:
  port: 8280
spring:
  #===========================================
  #   数据库配置
  #===========================================
  datasource:
    druid:
      url: jdbc:oracle:thin:@172.18.185.110:1521/fruit #数据库访问地址
      username: ajerp #数据库账号
      password: Tang1259 #数据库密码
      max-active: 1500 #最大连接数
      min-idle: 10 #最少空闲连接数
      max-wait: 60000 #最长等待时间
      driver-class-name: oracle.jdbc.OracleDriver #数据库驱动类
      validation-query: SELECT 1 FROM DUAL
      default-auto-commit: false
      pool-prepared-statements: true
      test-on-borrow: true
#===========================================
#   retrofit
#==========================================
retrofit:
  global-retry:
    enable: true #开启重试
    max-retries: 2 #重试次数
    interval-ms: 100 #重试间隔
  degrade:
    degrade-type: true
  global-log: #打印日志级别
    log-level: error
    enable: true

#===========================================
#   mybatis-plus
#===========================================
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: true
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #普通类中执行原生SQL
    enable-sql-runner: true
#  typeAliasesPackage: com.erp.**.entities


baidu:
  appid: 20240308001987150
  securityKey: oIabNhJlWQtWY9j8NhbS
