server:
  port: 8280
spring:
  #===========================================
  #   数据库配置
  #===========================================
  datasource:
    url: jdbc:postgresql://localhost:5432/transalte_datebase #数据库访问地址
    username: postgres #数据库账号
    password: root #数据库密码
    driver-class-name: org.postgresql.Driver #数据库驱动类
#===========================================
#   retrofit
#==========================================
retrofit:
  global-retry:
    enable: true #开启重试
    max-retries: 2 #重试次数
    interval-ms: 100 #重试间隔
  degrade:
    degrade-type: true
  global-log: #打印日志级别
    log-level: error
    enable: true

#===========================================
#   mybatis-plus
#===========================================
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: false
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #普通类中执行原生SQL
    enable-sql-runner: true


baidu:
  appid: 20240308001987150
  securityKey: oIabNhJlWQtWY9j8NhbS
